use std::str::FromStr as _;

use bbqr::{
    encode::Encoding,
    file_type::FileType,
    qr::Version,
    split::{Split, SplitOptions},
};
use bip39::{Language, Mnemonic};
use bitcoin::{
    Amount, NetworkKind, OutPoint, ScriptBuf, Sequence, Transaction, TxIn, TxOut, Witness,
    absolute::LockTime,
    bip32::{ChildNumber, Xpriv, Xpub},
    psbt::Psbt,
    secp256k1::Secp256k1,
    transaction::Version as TransactionVersion,
};
use keyteleport::{
    BackupPayload, BbqrOptions, DecryptedPayload, Error, MasterSecret, NoteRecord, NotesPayload,
    NotesRecord, NumericCode, Packet, PasswordRecord, Payload, PayloadKind, PsbtNonce, PsbtPacket,
    PsbtPayload, PsbtReceiverSession, PsbtSenderSession, ReceiverPacket, ReceiverSession,
    ReceiverSessionSecret, SenderPacket, SenderSession, TeleportPassword, UnknownPayload,
    VaultPayload, VaultSecret, XprvPayload, XprvWireFormat,
};
use proptest::prelude::*;

const RECEIVER_SECRET: [u8; 32] = [1; 32];
const RECEIVER_SECRET_2: [u8; 32] = [2; 32];
const PASSWORD_BYTES: [u8; 5] = [0x12, 0x34, 0x56, 0x78, 0x9a];
const XPRV: &str = "xprv9s21ZrQH143K4BwRCYKSEPwcAMYweWkfKLURabnnv2GLNhJN1LSCgDQyGWyNcat72najQKwyshCBXWfHHVbcdxPAZPqByMyWDbWp5SjCfEa";
const KEYTELEPORT_DOC_EXAMPLE: &str =
    "https://keyteleport.com/#B$2R0100VHT2AGUUH7KUZUUSTOWOIWHJX3XM7GA2N4BHQOXDFHXLVHVA7K6ZO";
const EXPECTED_RECEIVER_PACKET: &str =
    "c6cc594473287ba6a0af8b6a5f5183cf51cb750d1df10c8a6cc5236fe43fc5e5dc";

// fixtures generated by COLDCARD firmware testing/teleport_protocol.py at bcc2c382

#[test]
fn mnemonic_payload_roundtrips_for_supported_word_counts() {
    for entropy_len in [16, 24, 32] {
        let mnemonic = Mnemonic::from_entropy(&vec![0_u8; entropy_len]).unwrap();
        let expected = mnemonic.clone();
        let decoded = encoded_roundtrip(Payload::mnemonic(mnemonic).unwrap());

        assert_eq!(decoded, Payload::Mnemonic(expected));
    }
}

#[test]
fn mnemonic_payload_rejects_unsupported_word_counts() {
    for entropy_len in [20, 28] {
        let mnemonic = Mnemonic::from_entropy(&vec![0_u8; entropy_len]).unwrap();

        assert!(matches!(
            Payload::mnemonic(mnemonic),
            Err(Error::UnsupportedMnemonicWordCount(15 | 21))
        ));
    }
}

#[test]
fn mnemonic_payload_rejects_non_english_word_lists() {
    let japanese = Mnemonic::from_entropy_in(Language::Japanese, &[0; 16]).unwrap();

    assert!(matches!(Payload::mnemonic(japanese), Err(Error::UnsupportedMnemonicLanguage)));
}

#[test]
fn ambiguous_english_words_encode_without_language_detection() {
    let decoded =
        DecryptedPayload::from_bytes(vec![b's', 0x80, 0, 0, 0, 0, 0x7a]).unwrap().decode().unwrap();

    assert!(decoded.encode().is_ok());
}

#[test]
fn compact_xprv_roundtrip_preserves_key_and_requires_caller_network() {
    let decoded = encoded_roundtrip(Payload::xprv(XPRV).unwrap());
    let Payload::Xprv(xprv) = decoded else {
        panic!("expected XPRV");
    };

    assert_eq!(xprv.network(), None);
    assert_eq!(xprv.wire_format(), XprvWireFormat::Stash);
    assert_eq!(xprv.encode_string(NetworkKind::Main), XPRV);

    let testnet = Xpriv::new_master(NetworkKind::Test, &[42; 32]).unwrap();
    let decoded = encoded_roundtrip(Payload::xprv(testnet.to_string()).unwrap());
    let Payload::Xprv(xprv) = decoded else {
        panic!("expected XPRV");
    };

    assert_eq!(xprv.network(), None);
    assert_eq!(xprv.encode_string(NetworkKind::Test), testnet.to_string());
}

#[test]
fn full_xprv_roundtrip_preserves_encoded_network() {
    for network in [NetworkKind::Main, NetworkKind::Test] {
        let expected = Xpriv::new_master(network, &[42; 32]).unwrap();
        let decoded = encoded_roundtrip(Payload::full_xprv(expected.to_string()).unwrap());
        let Payload::Xprv(xprv) = decoded else {
            panic!("expected XPRV");
        };

        assert_eq!(xprv.network(), Some(network));
        assert_eq!(xprv.wire_format(), XprvWireFormat::Full);
        assert_eq!(xprv.to_xpriv(network), expected);
    }
}

#[test]
fn xprv_validation_rejects_invalid_and_derived_keys() {
    assert!(matches!(
        XprvPayload::parse("xprv9s21ZrQH143K4invalid"),
        Err(Error::InvalidXprvPayload)
    ));

    let child = Xpriv::from_str(XPRV)
        .unwrap()
        .derive_priv(&Secp256k1::new(), &[ChildNumber::from_normal_idx(0).unwrap()])
        .unwrap();

    assert!(matches!(Payload::xprv(child.to_string()), Err(Error::NonMasterXprvPayload)));
}

#[test]
fn raw_master_secret_roundtrip_preserves_length_and_trailing_zeroes() {
    for length in [16, 17, 32, 64] {
        let mut bytes = (0..length).map(|value| value as u8).collect::<Vec<_>>();
        *bytes.last_mut().unwrap() = 0;
        let decoded = encoded_roundtrip(Payload::master_secret(bytes.clone()).unwrap());
        let Payload::MasterSecret(secret) = decoded else {
            panic!("expected master secret");
        };

        assert_eq!(secret.expose_bytes(), bytes);
        assert_eq!(
            secret.derive_xprv(NetworkKind::Main).unwrap().to_xpriv(NetworkKind::Main),
            Xpriv::new_master(NetworkKind::Main, &bytes).unwrap()
        );
    }

    assert!(matches!(MasterSecret::new(vec![0; 15]), Err(Error::InvalidMasterSecretLength(15))));
    assert!(matches!(MasterSecret::new(vec![0; 65]), Err(Error::InvalidMasterSecretLength(65))));
}

#[test]
fn secure_notes_roundtrip_preserves_record_types_and_fields() {
    let records = vec![
        NotesRecord::Note(
            NoteRecord::new("Recovery".into(), "stored in safe".into(), "wallet".into()).unwrap(),
        ),
        NotesRecord::Password(
            PasswordRecord::new(
                "Exchange".into(),
                "alice".into(),
                "correct horse".into(),
                "example.com".into(),
                "2FA in safe".into(),
                "finance".into(),
            )
            .unwrap(),
        ),
    ];
    let decoded = encoded_roundtrip(Payload::notes(records.clone()).unwrap());

    assert_eq!(decoded, Payload::Notes(NotesPayload::new(records).unwrap()));
}

#[test]
fn secure_notes_decode_uses_user_field_as_record_discriminator() {
    let payload = DecryptedPayload::from_bytes(
        br#"n[{"title":"note","misc":"text","extra":true},{"title":"login","user":"","password":"secret"}]"#
            .to_vec(),
    )
    .unwrap()
    .decode()
    .unwrap();
    let Payload::Notes(notes) = payload else {
        panic!("expected notes");
    };

    assert!(matches!(notes.records()[0], NotesRecord::Note(_)));
    assert!(matches!(notes.records()[1], NotesRecord::Password(_)));
}

#[test]
fn secure_notes_reject_invalid_record_shapes() {
    for value in [
        br#"n[]"#.as_slice(),
        br#"n[{"title":""}]"#.as_slice(),
        br#"n[{"title":"note","password":"secret"}]"#.as_slice(),
        br#"nnot-json"#.as_slice(),
    ] {
        assert!(matches!(
            DecryptedPayload::from_bytes(value.to_vec()).unwrap().decode(),
            Err(Error::InvalidNotesPayload)
        ));
    }
}

#[test]
fn seed_vault_roundtrip_preserves_metadata_and_each_secret_type() {
    let secrets = [
        VaultSecret::Mnemonic(test_mnemonic_12()),
        VaultSecret::Xprv(XprvPayload::parse(XPRV).unwrap()),
        VaultSecret::MasterSecret(MasterSecret::new(vec![3; 32]).unwrap()),
    ];

    for secret in secrets {
        let expected =
            VaultPayload::new("A1b2C3d4", secret, "primary".into(), "m/84h".into()).unwrap();
        let decoded = encoded_roundtrip(Payload::vault(expected));
        let Payload::Vault(vault) = decoded else {
            panic!("expected vault");
        };

        assert_eq!(vault.fingerprint(), "A1B2C3D4");
        assert_eq!(vault.label(), "primary");
        assert_eq!(vault.origin(), "m/84h");
        match vault.secret() {
            VaultSecret::Mnemonic(value) => assert_eq!(value, &test_mnemonic_12()),
            VaultSecret::Xprv(value) => {
                assert_eq!(value.encode_string(NetworkKind::Main), XPRV)
            }
            VaultSecret::MasterSecret(value) => assert_eq!(value.expose_bytes(), &[3; 32]),
        }
    }
}

#[test]
fn seed_vault_accepts_uppercase_and_odd_length_firmware_hex() {
    let decoded = DecryptedPayload::from_bytes(br#"v["AABBCCDD","101","legacy","m"]"#.to_vec())
        .unwrap()
        .decode()
        .unwrap();
    let Payload::Vault(vault) = decoded else {
        panic!("expected vault");
    };
    let VaultSecret::MasterSecret(secret) = vault.secret() else {
        panic!("expected master secret");
    };

    assert_eq!(secret.expose_bytes(), &[0x10, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0]);
    assert_eq!(vault.fingerprint(), "AABBCCDD");
}

#[test]
fn seed_vault_rejects_invalid_fingerprint_hex_and_shape() {
    assert!(matches!(
        VaultPayload::new(
            "123",
            VaultSecret::Mnemonic(test_mnemonic_12()),
            String::new(),
            String::new()
        ),
        Err(Error::InvalidVaultPayload)
    ));

    for value in [
        br#"v["AABBCCDD","zz","label","origin"]"#.as_slice(),
        br#"v["AABBCCDD"]"#.as_slice(),
        br#"v{}"#.as_slice(),
    ] {
        assert!(matches!(
            DecryptedPayload::from_bytes(value.to_vec()).unwrap().decode(),
            Err(Error::InvalidVaultPayload)
        ));
    }
}

#[test]
fn backup_psbt_and_unknown_payloads_are_lossless() {
    let backup = b"# Coldcard backup file\nmnemonic = secret\n".to_vec();
    let decoded = encoded_roundtrip(Payload::backup(backup.clone()).unwrap());
    let Payload::Backup(decoded_backup) = decoded else {
        panic!("expected backup");
    };
    assert_eq!(decoded_backup.expose_bytes(), backup);
    assert_eq!(decoded_backup.as_text().unwrap().as_bytes(), backup);

    let psbt = minimal_psbt();
    let decoded = encoded_roundtrip(Payload::psbt(psbt.clone()).unwrap());
    let Payload::Psbt(decoded_psbt) = decoded else {
        panic!("expected PSBT");
    };
    assert_eq!(decoded_psbt.expose_bytes(), psbt);
    assert!(decoded_psbt.parse().is_ok());

    let decoded = encoded_roundtrip(Payload::unknown(b'q', vec![0, 1, 2, 0]).unwrap());
    let Payload::Unknown(unknown) = decoded else {
        panic!("expected unknown payload");
    };
    assert_eq!(unknown.code(), b'q');
    assert_eq!(unknown.expose_body(), [0, 1, 2, 0]);
}

#[test]
fn raw_payload_validation_rejects_empty_and_malformed_values() {
    assert!(matches!(DecryptedPayload::from_bytes(Vec::new()), Err(Error::InvalidPayload)));
    assert!(matches!(BackupPayload::new(Vec::new()), Err(Error::InvalidBackupPayload)));
    assert!(matches!(PsbtPayload::new(b"psbt\xff".to_vec()), Err(Error::InvalidPsbtPayload)));
    assert!(matches!(UnknownPayload::new(b's', Vec::new()), Err(Error::KnownPayloadCode(b's'))));

    let binary_backup = BackupPayload::new(vec![0xff]).unwrap();
    assert!(matches!(binary_backup.as_text(), Err(Error::InvalidBackupPayload)));
}

#[test]
fn decrypted_unknown_payload_retains_exact_wire_bytes() {
    let wire = vec![0xf0, 0, 0xff, 1, 0];
    let decrypted = DecryptedPayload::from_bytes(wire.clone()).unwrap();

    assert_eq!(decrypted.kind(), PayloadKind::Unknown(0xf0));
    assert_eq!(decrypted.expose_bytes(), wire);
    assert_eq!(decrypted.clone().decode().unwrap().encode().unwrap(), decrypted);
}

#[test]
fn receiver_session_matches_coldcard_protocol_vector() {
    let receiver = deterministic_receiver(RECEIVER_SECRET);
    let request = receiver.request().unwrap();

    assert_eq!(request.numeric_code.as_str(), "88805930");
    assert_eq!(hex_string(request.packet.as_bytes()), EXPECTED_RECEIVER_PACKET);
    assert!(request.packet.to_bbqr_part().unwrap().starts_with("B$2R0100"));
}

#[test]
fn receiver_secret_restores_the_same_active_request() {
    let original = deterministic_receiver(RECEIVER_SECRET);
    let original_request = original.request().unwrap();
    let secret = original.export_secret();
    let restored = ReceiverSession::from_secret(secret).unwrap();

    assert_eq!(restored.request().unwrap(), original_request);
    assert!(!format!("{:?}", original.export_secret()).contains("010101"));
}

#[test]
fn receiver_returns_state_after_wrong_packet_and_password() {
    let receiver = deterministic_receiver(RECEIVER_SECRET);
    let request = receiver.request().unwrap();
    let sender = SenderSession::new(&request.packet, &request.numeric_code).unwrap();
    let response = sender.send(Payload::mnemonic(test_mnemonic_12()).unwrap()).unwrap();

    let wrong_receiver = deterministic_receiver(RECEIVER_SECRET_2);
    let error = wrong_receiver.decode_step1(&response.packet).unwrap_err();
    assert!(matches!(error.error(), Error::Checksum));
    let (wrong_receiver, _) = error.into_parts();
    assert_eq!(
        wrong_receiver.request().unwrap(),
        deterministic_receiver(RECEIVER_SECRET_2).request().unwrap()
    );

    let pending = receiver.decode_step1(&response.packet).unwrap();
    let mut wrong_bytes = *response.password.expose_bytes();
    wrong_bytes[0] ^= 0xff;
    let error = pending.complete(&TeleportPassword::from_bytes(wrong_bytes)).unwrap_err();
    assert!(matches!(error.error(), Error::Checksum));
    let (pending, _) = error.into_parts();
    let transfer = pending.complete(&response.password).unwrap();

    assert!(matches!(transfer.payload(), Payload::Mnemonic(_)));
}

#[test]
fn decoded_transfer_requires_explicit_accept_or_reject() {
    let receiver = deterministic_receiver(RECEIVER_SECRET);
    let request = receiver.request().unwrap();
    let sender = SenderSession::new(&request.packet, &request.numeric_code).unwrap();
    let response = sender.send(Payload::mnemonic(test_mnemonic_12()).unwrap()).unwrap();
    let transfer =
        receiver.decode_step1(&response.packet).unwrap().complete(&response.password).unwrap();
    let restored = transfer.reject();

    assert_eq!(restored.request().unwrap(), request);

    let sender = SenderSession::new(&request.packet, &request.numeric_code).unwrap();
    let response = sender.send(Payload::mnemonic(test_mnemonic_12()).unwrap()).unwrap();
    let accepted = restored
        .decode_step1(&response.packet)
        .unwrap()
        .complete(&response.password)
        .unwrap()
        .accept();

    assert!(matches!(accepted, Payload::Mnemonic(_)));
}

#[test]
fn password_and_receiver_code_parsers_normalize_display_input() {
    let password = TeleportPassword::from_bytes(PASSWORD_BYTES);
    let lowercase = password.grouped().to_ascii_lowercase().replace(' ', "-");
    let code = NumericCode::from_str("12 34 56 78").unwrap();

    assert_eq!(TeleportPassword::from_str(&lowercase).unwrap(), password);
    assert_eq!(password.grouped(), "CI 2F M6 E2");
    assert_eq!(code.as_str(), "12345678");
    assert_eq!(code.grouped(), "12 34 56 78");
    assert!(matches!(TeleportPassword::from_str("AAAAAAA9"), Err(Error::InvalidTeleportPassword)));
    assert!(matches!(NumericCode::from_str("1234567x"), Err(Error::InvalidNumericCode)));
}

#[test]
fn packet_urls_are_strict_and_documentation_example_decodes() {
    let packet = Packet::from_url(KEYTELEPORT_DOC_EXAMPLE).unwrap();
    assert!(matches!(packet, Packet::Receiver(_)));
    assert!(Packet::from_url(&packet.to_url().unwrap()).is_ok());

    let mixed_case = KEYTELEPORT_DOC_EXAMPLE.replace("keyteleport.com", "KeyTeleport.com");
    let part = KEYTELEPORT_DOC_EXAMPLE.split_once('#').unwrap().1;
    assert!(Packet::from_url(&mixed_case).is_ok());
    assert!(Packet::from_url(part).is_ok());
    assert!(Packet::from_url(&format!("keyteleport.com/#{part}")).is_ok());

    for invalid in [
        format!("http://keyteleport.com/#{part}"),
        format!("https://example.com/#{part}"),
        format!("https://user@keyteleport.com/#{part}"),
        format!("https://keyteleport.com:444/#{part}"),
        format!("https://keyteleport.com/path/#{part}"),
        format!("https://keyteleport.com/?x=1#{part}"),
        "https://keyteleport.com/#not-bbqr".into(),
    ] {
        assert!(Packet::from_url(&invalid).is_err(), "{invalid}");
    }
}

#[test]
fn all_packet_types_roundtrip_through_single_part_bbqr() {
    let receiver = deterministic_receiver(RECEIVER_SECRET);
    let request = receiver.request().unwrap();
    let sender = SenderSession::new(&request.packet, &request.numeric_code).unwrap();
    let response = sender.send(Payload::mnemonic(test_mnemonic_12()).unwrap()).unwrap();
    let psbt = PsbtPacket::from_parts(PsbtNonce::new(7).unwrap(), vec![1, 2, 3, 4, 5]).unwrap();

    for expected in
        [Packet::Receiver(request.packet), Packet::Sender(response.packet), Packet::Psbt(psbt)]
    {
        let decoded = Packet::from_bbqr_part(&expected.to_bbqr_part().unwrap()).unwrap();
        assert_eq!(decoded, expected);
    }
}

#[test]
fn multipart_bbqr_roundtrip_accepts_out_of_order_parts() {
    let receiver = deterministic_receiver(RECEIVER_SECRET);
    let request = receiver.request().unwrap();
    let sender = SenderSession::new(&request.packet, &request.numeric_code).unwrap();
    let response = sender.send(Payload::backup(vec![42; 2_048]).unwrap()).unwrap();
    let expected = Packet::Sender(response.packet);
    let split = expected
        .to_bbqr(BbqrOptions {
            min_parts: 2,
            max_parts: 100,
            min_version: Version::V01,
            max_version: Version::V05,
        })
        .unwrap();
    let mut parts = split.parts;
    parts.reverse();

    assert!(parts.len() > 1);
    assert_eq!(Packet::from_bbqr_parts(parts).unwrap(), expected);
}

#[test]
fn keyteleport_rejects_non_base32_bbqr() {
    let receiver = deterministic_receiver(RECEIVER_SECRET);
    let bytes = receiver.request().unwrap().packet.as_bytes().to_vec();
    let split = Split::try_from_data(
        &bytes,
        FileType::KeyTeleportReceiver,
        SplitOptions {
            encoding: Encoding::Hex,
            min_split_number: 1,
            max_split_number: 1,
            min_version: Version::V01,
            max_version: Version::V40,
        },
    )
    .unwrap();

    assert!(matches!(Packet::from_bbqr_parts(split.parts), Err(Error::InvalidBbqrEncoding)));
}

#[test]
fn packet_parser_rejects_non_ascii_input_without_panicking() {
    assert!(matches!(Packet::from_bbqr_part("\u{fffd}"), Err(Error::InvalidPacket)));
    assert!(matches!(
        Packet::from_bbqr_parts(vec!["B$2R0100\u{fffd}".into()]),
        Err(Error::InvalidPacket)
    ));
}

#[test]
fn packet_constructors_enforce_protocol_boundaries() {
    assert!(matches!(ReceiverPacket::new(vec![0; 32]), Err(Error::InvalidReceiverPacket)));
    assert!(ReceiverPacket::new(vec![0; 33]).is_ok());
    assert!(matches!(ReceiverPacket::new(vec![0; 34]), Err(Error::InvalidReceiverPacket)));

    assert!(matches!(SenderPacket::new(vec![0; 38]), Err(Error::InvalidSenderPacket)));
    assert!(matches!(PsbtPacket::new(vec![0; 8]), Err(Error::InvalidPsbtPacket)));
    assert!(matches!(
        PsbtNonce::new(1 << 28),
        Err(Error::InvalidPsbtNonce(value)) if value == 1 << 28
    ));
    assert_eq!(PsbtNonce::new((1 << 28) - 1).unwrap().value(), (1 << 28) - 1);
}

#[test]
fn multisig_psbt_e_packet_roundtrips_and_retries_password() {
    let (sender, sender_xpub, receiver, receiver_xpub) = multisig_keys();
    let response = PsbtSenderSession::new(&sender, &receiver_xpub)
        .unwrap()
        .send(PsbtPayload::new(minimal_psbt()).unwrap())
        .unwrap();
    let receiver_session =
        PsbtReceiverSession::new(&receiver, &sender_xpub, response.packet.nonce()).unwrap();
    let pending = receiver_session.decode_step1(&response.packet).unwrap();
    let mut wrong = *response.password.expose_bytes();
    wrong[4] ^= 1;

    assert!(matches!(pending.complete(&TeleportPassword::from_bytes(wrong)), Err(Error::Checksum)));
    assert_eq!(pending.complete(&response.password).unwrap().expose_bytes(), minimal_psbt());
}

#[test]
fn multisig_psbt_e_packet_rejects_wrong_key_nonce_and_payload() {
    let (sender, sender_xpub, receiver, receiver_xpub) = multisig_keys();
    let response = PsbtSenderSession::new(&sender, &receiver_xpub)
        .unwrap()
        .send(PsbtPayload::new(minimal_psbt()).unwrap())
        .unwrap();
    let wrong_sender = Xpriv::new_master(NetworkKind::Main, &[9; 32]).unwrap();
    let wrong_sender_xpub = Xpub::from_priv(&Secp256k1::new(), &wrong_sender);
    let wrong_key =
        PsbtReceiverSession::new(&receiver, &wrong_sender_xpub, response.packet.nonce()).unwrap();
    assert!(matches!(wrong_key.decode_step1(&response.packet), Err(Error::Checksum)));

    let other_nonce = PsbtNonce::new((response.packet.nonce().value() + 1) % (1 << 28)).unwrap();
    let wrong_nonce = PsbtReceiverSession::new(&receiver, &sender_xpub, other_nonce).unwrap();
    assert!(matches!(
        wrong_nonce.decode_step1(&response.packet),
        Err(Error::PsbtNonceMismatch { .. })
    ));
}

#[test]
fn public_debug_output_redacts_secret_values() {
    let mnemonic = test_mnemonic_12();
    let mnemonic_text = mnemonic.to_string();
    let password = TeleportPassword::from_bytes(PASSWORD_BYTES);
    let notes =
        NoteRecord::new("private title".into(), "private text".into(), String::new()).unwrap();
    let xprv = XprvPayload::parse(XPRV).unwrap();

    assert!(!format!("{password:?}").contains(&password.as_display_text()));
    assert!(!format!("{:?}", Payload::Mnemonic(mnemonic)).contains(&mnemonic_text));
    assert!(!format!("{notes:?}").contains("private text"));
    assert!(!format!("{xprv:?}").contains(XPRV));
}

proptest! {
    #[test]
    fn arbitrary_master_secrets_roundtrip(
        bytes in prop::collection::vec(any::<u8>(), 16..=64)
    ) {
        let decoded = encoded_roundtrip(Payload::master_secret(bytes.clone()).unwrap());
        let Payload::MasterSecret(secret) = decoded else {
            return Err(TestCaseError::fail("expected master secret"));
        };

        prop_assert_eq!(secret.expose_bytes(), bytes);
    }

    #[test]
    fn arbitrary_unknown_payloads_roundtrip(
        code in any::<u8>(),
        body in prop::collection::vec(any::<u8>(), 0..512)
    ) {
        prop_assume!(!matches!(code, b's' | b'x' | b'n' | b'v' | b'p' | b'b'));
        let expected = DecryptedPayload::from_bytes(
            std::iter::once(code).chain(body).collect()
        ).unwrap();
        let encoded = expected.clone().decode().unwrap().encode().unwrap();

        prop_assert_eq!(encoded, expected);
    }

    #[test]
    fn arbitrary_nonempty_backups_roundtrip(
        bytes in prop::collection::vec(any::<u8>(), 1..1024)
    ) {
        let decoded = encoded_roundtrip(Payload::backup(bytes.clone()).unwrap());
        let Payload::Backup(backup) = decoded else {
            return Err(TestCaseError::fail("expected backup"));
        };

        prop_assert_eq!(backup.expose_bytes(), bytes);
    }

    #[test]
    fn all_password_bytes_roundtrip_text(bytes in any::<[u8; 5]>()) {
        let expected = TeleportPassword::from_bytes(bytes);
        let decoded = TeleportPassword::from_str(&expected.grouped()).unwrap();

        prop_assert_eq!(decoded, expected);
    }
}

fn encoded_roundtrip(payload: Payload) -> Payload {
    payload.encode().unwrap().decode().unwrap()
}

fn deterministic_receiver(secret: [u8; 32]) -> ReceiverSession {
    ReceiverSession::from_secret(ReceiverSessionSecret::from_bytes(secret).unwrap()).unwrap()
}

fn test_mnemonic_12() -> Mnemonic {
    Mnemonic::from_entropy(&[0_u8; 16]).unwrap()
}

fn minimal_psbt() -> Vec<u8> {
    let transaction = Transaction {
        version: TransactionVersion::TWO,
        lock_time: LockTime::ZERO,
        input: vec![TxIn {
            previous_output: OutPoint::null(),
            script_sig: ScriptBuf::new(),
            sequence: Sequence::MAX,
            witness: Witness::new(),
        }],
        output: vec![TxOut { value: Amount::ZERO, script_pubkey: ScriptBuf::new() }],
    };

    Psbt::from_unsigned_tx(transaction).unwrap().serialize()
}

fn multisig_keys() -> (Xpriv, Xpub, Xpriv, Xpub) {
    let sender = Xpriv::new_master(NetworkKind::Main, &[1; 32]).unwrap();
    let receiver = Xpriv::new_master(NetworkKind::Main, &[2; 32]).unwrap();
    let secp = Secp256k1::new();
    let sender_xpub = Xpub::from_priv(&secp, &sender);
    let receiver_xpub = Xpub::from_priv(&secp, &receiver);

    (sender, sender_xpub, receiver, receiver_xpub)
}

fn hex_string(bytes: &[u8]) -> String {
    bytes.iter().map(|byte| format!("{byte:02x}")).collect()
}
