[package]
name = "keyteleport-fuzz"
version = "0.0.0"
publish = false
edition = "2024"

[package.metadata]
cargo-fuzz = true

[dependencies]
libfuzzer-sys = "0.4.10"
keyteleport = { path = ".." }

[[bin]]
name = "packet"
path = "fuzz_targets/packet.rs"
test = false
doc = false
bench = false

[[bin]]
name = "payload"
path = "fuzz_targets/payload.rs"
test = false
doc = false
bench = false

[workspace]
members = ["."]
