name: CI

on:
  workflow_dispatch: {}
  push:
    branches:
      - master
  pull_request:
    branches:
      - master


jobs:
  rustfmt:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout sources
        uses: actions/checkout@v6

      - name: Install stable toolchain with rustfmt available
        uses: dtolnay/rust-toolchain@stable
        with:
          components: rustfmt

      - name: Run rustfmt
        run: cargo fmt --all -- --check

  clippy:
    runs-on: ubuntu-latest
    env:
      RUSTFLAGS: -D warnings
    steps:
      - uses: actions/checkout@v6
      - uses: dtolnay/rust-toolchain@stable
        with:
          components: clippy

      - name: Cache Rust builds
        uses: Swatinem/rust-cache@v2
        with:
          cache-bin: false
          prefix-key: v1-rust

      - run: cargo clippy --all-targets --all-features -- -D warnings

  test:
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest]
    runs-on: ${{ matrix.os }}
    env:
      RUSTFLAGS: -D warnings
    steps:
      - uses: actions/checkout@v6

      - name: Install stable toolchain
        uses: dtolnay/rust-toolchain@stable

      - name: Cache Rust builds
        uses: Swatinem/rust-cache@v2
        with:
          cache-bin: false
          prefix-key: v1-rust

      - name: Run tests
        run: cargo test
